#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
    indexn = []   
    newarr = [None] * n

    for i,u in enumerate(zip(*arr)):
        if i == k:
            indexn = sorted(range(len(u)), key=lambda k: u[k])      
    
    for i,u in enumerate(indexn):
        newarr[i] = arr[u]

    for i in newarr:
        print(*i)
